id: AE50F644C
title: Supplement to the Omniscient Ngorchen Kunga Zangpo’s Prayer to the Lineage
  of Parting from the Four Attachments
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:02:51.904131
  last_modified_at: 2022-03-01 05:02:51.904136
