id: AE50F644C
title: Prayer to the Lineage of Parting from the Four Attachments
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:02:51.902045
  last_modified_at: 2022-03-01 05:02:51.902053
